cargo-features = ["strip"]

[package]
name = "histdb-rs"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
chrono = { version = "0.4", features = ["serde"] }
comfy-table = "1"
csv = "1"
directories = "3"
glob = "0.3"
hostname = "0.3"
humantime = "2"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1"
rusqlite = "0.24"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
thiserror = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
strip = "symbols"
